admins:
  mentor_1:
    name: "Mentor (Thomas)"
    avatar: "/avatars/admin.svg"
  admin_local:
    name: "Lokal-Admin"
    avatar: "/avatars/admin_local.svg"

users:
  student_a:
    name: "Alice"
    avatar: "/avatars/student.svg"
  student_b:
    name: "Bob"
    avatar: "/avatars/student_b.svg"
  student_c:
    name: "Charlie"
    avatar: "/avatars/student_c.svg"

