model_list:

  - model_name: gg1-g3-flash
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/GOOGLE_API_KEY

  - model_name: or-gemini-3-flash
    litellm_params:
      model: openrouter/google/google-gemini-3-flash-preview
      api_key: os.environ/OPENROUTER_API_KEY

litellm_settings:
  # Dieser Eintrag sorgt dafür, dass setup_custom_api ausgeführt wird:
  custom_callback_wrapper: "middleware"

  success_callback: ["database"] # Aktiviert das Speichern jedes Calls in Postgres
  callbacks: ["middleware.set_context_callback"]  
  allow_user_auth: true

  
general_settings: 
  master_key: sk-1234 
