---
api:
  :name: api
  :command: ruby -e "require 'socket'; server = TCPServer.new(ENV['API_PORT'].to_i);
    loop { client = server.accept; client.puts 'HTTP/1.1 200 OK\n\nOK'; client.close
    }"
  :port: 3101
  :pid: 1453
  :state: :running
  :last_error: 
  :started_at: 2026-01-04 02:43:03.775233844 +01:00
  :depends_on: []
