layers:
  tag:
    priority: 100
    git_base: "https://github.com/tag-makerspace"
  official:
    priority: 10
    git_base: "https://github.com/raspberrypilearning"
    api_base: "https://learning-admin.raspberrypi.org/api/v1"

sync:
  pathways:
    official:
      - scratch-intro
      - physical-computing-with-scratch-and-the-raspberry-pi
